### PR TITLE
Updating the textbook to latest Jupyter Book

### PR DESCRIPTION
**Pull request by choldgraf**
This is going to be a large refresh for the repository, it upgrades to the latest jupyter book (which is a lot, since this repo was using a very old version).

### CODE REVIEW

**Comment by choldgraf** [comment]
@dcroce this is the upgrade from the old to the new book version. I believe all content should be in there, though I might have missed a few things here and there.

Here's a preview of what it looks like:

https://7-144916370-gh.circle-artifacts.com/0/html/Chapter_01/00_Fundamentals.html

I think that the way forward is to:

1. Decide if this PR is **broadly** correct from the demo page linked above. If so, then we replace the current gh-pages branch with this PR. (I think this PR is too big to keep track of the actual diff)
2. We fix small errors, missing pages, etc in subsequent PRs.

Let me know what you think

**Comment by dcroce** [comment]
@choldgraf Awesome looks great!
Only issues I see:
1. Numbering is off by one, easy fix.
2. Search is missing. If it's just finding the notebook, easy fix. Otherwise potentially more difficult but admittedly not a critical feature. 
3. Jupyterhub is not set up yet. Not sure if this is a bug or just not directing to the right place. 

I am otherwise fine with the changes, but don't want the book to go live until the clean up is done. There is a homework assignment due tomorrow at noon and I know many of them will be referring to the book tonight. If we merge will the current book be replaced by this? If so, we should cleanup before the merge.

**Comment by choldgraf** [comment]
Ah OK, I didn't realize the students were already using the site. OK lemme try fixing that up.

When you say the jupyterhub doesn't work, what do you mean?

**Comment by choldgraf** [comment]
Oh and re: search, look in the top right

**Comment by dcroce** [comment]
Just getting rid of the search line in the sidebar should fix the numbering. Great to see the search is at the top. 

As for Jupyterhub, I'm getting a "404 : Not Found, You are requesting a page that does not exist!" error page when I click the Jupyterhub button on top of any of the notebook sections. It does seem like it's directing to the correct place, i.e. https://prob140.datahub.berkeley.edu/user/dcroce/notebooks/textbook/content/Chapter_01/02_Equally_Likely_Outcomes.ipynb. Content is not a folder in the current textbook repo but I think once we merge this it may be the right place.

**Comment by choldgraf** [comment]
re: numbering, see the latest version:

https://9-144916370-gh.circle-artifacts.com/0/html/Chapter_01/00_Fundamentals.html

looks OK?

re: the jupyterhub links, I think you're right - once it's merged then  I think that the links should work. Do they look correct to you?

```
https://prob140.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com//prob140/textbook&branch=gh-pages&subPath=content%2FChapter_01%2F00_Fundamentals.ipynb&app=notebook
```

**Comment by dcroce** [comment]
Numbering looks better. The double numbering isn't ideal but can be fixed once we've made the merge. Will be easy to either remove numbering altogether or just remove the "Chapter x" in the titles. 

Links look correct but we'll confirm after the merge.

**Pull request merged**
